### PR TITLE
Added missing bits to make the plugin work

### LINKED ISSUE #1: Plugin not working
Hi,

Firstly, very thankful to this useful mock api tool.

I found that this plugin has conflict with [ng-apimock](https://github.com/mdasberg/ng-apimock). The api calling with the incorrect request url or body.

After I migrate it to modularized `ng-apimock/core`, I found that `cy.selectScenario` has no use for changing scenario in cypress though it return 200 but nothing happens.

BTW, how did you make async/await work in cypress? AFAIK, `.then` is the only way to operate with Promise in cypress without 3rd party plugins.

### LINKED ISSUE #3: Does this plugin supporting?
Hello!
Does this plugin supporting?  I think it's not working.

### PR DESCRIPTION
**Pull request by onderceylan**
Hi there,

First of, thanks for the great library of ng-apimock! This PR adds missing blocks to make cypress-plugin work in the user land.

The main problem with the plugin was, using **baseUrl** config of cypress as ngapimock url. This cannot work because baseUrl of cypress represents the app url that cypress executes tests against. And, it shouldn't conflict with ngapimock server url.

The other major issue was, using the cookie value on request being made to ng-apimock server. While this cookie is set, all requests fail. Since the use of cookie is not documented and seemed unused, I removed the related APIs as well.

There were also some other issues, like missing packages -urljoin and missing types in tsconfig file.

I added type definitions to the project to enable command execution in a type safe way.

Finally, I did some maintenance on the project that you'll see the details of in the PR. Hopefully you agree with the decisions made on the way to make this plugin work and release a package update ASAP! Thanks!

* 37bbeee Dep upgrade to replace vulnerable packages
* fb2bdc0 Added missing dependency urljoin
* 55025d0 Streamlined package constraints and added missing node type
* 6d71fb1 Removed setting cookie that is breaking plugin functionality
* fcf713d Added typescript definition for cy commands of the plugin
* 63365d0 Updated docs and ignored cypress.json

fixes #1 
fixes #3

### CODE REVIEW

**Comment by mdasberg** [comment]
@onderceylan thanks for the pr. I will look into it tonight.

**Comment by onderceylan** [comment]
@mdasberg, is there anything I should improve/change in this PR?

**Comment by mdasberg** [comment]
@onderceylan I just released v1.0.2

Thanks for the pr.

**Comment by onderceylan** [comment]
@mdasberg, and thank you for the chore and release! I've just replaced my fork in my project and all is good.

**Pull request merged**
